### ISSUE TITLE
[Question] Error SMF

### ISSUE THREAD

**Issue by andrewscaya** [andrewscaya/mod_simpleemailform#1]
Hello Doug,

I wrote to You last week about problem with attachment in simple mail form. If is possible please look at this problem.
http://autoimpr.webd.pl/strona1/index.php/form
Could not access file: /home/autoimpr/public_html/strona1/skuppojazdow/
I have two fields with attachments - when I try send one attachment I see this error when I send two all is OK.

Regards

Mateusz

**Comment by andrewscaya** [comment]
New unit tests have been added to cover the logical possibilities that the patch's code has introduced into the module.  The current code coverage is around 30%.

Also, a latent bug was also discovered and fixed.

Finally, the code does not pass the PHP 5.3 tests (Joomla's minimum requirement is 5.3.10 and its recommended requirement is 5.6+).  We will have to remove 5.3 from the version matrix and update the minumum requirements for this module to 5.4+.

**Comment by andrewscaya** [comment]
Blackbox testing the suggested patch.

**Comment by andrewscaya** [comment]
Release 1.8.8 is now frozen.  Release candidate under final review.

**Comment by bplight** [comment]
Hello.Yesterday viewed this bug. 
Is it possible to make in upload field settings Required/nonRequired selector?
Awaiting for improved release!
Thanks for your work!

**Comment by andrewscaya** [comment]
Hello bplight,

Thanks for your suggestion.  We are including it in our roadmap for version 2.0.0.

Regards,

**Comment by bplight** [comment]
One more suggestion.
Could you please add a prefix to the name of uploaded file?
It`s nessecary for me  that files were not overwritten.
Attached file is uploaded with the same name to thr folder. 
The prefix may include year_month_date_time. 
(I peeped it in chronoforms joomla extention)

**Comment by andrewscaya** [comment]
Hello bplight,

We thank you for your suggestions and we might implement this last one in a future release.

Regards,

**Comment by andrewscaya** [comment]
Version 1.8.8 released.

**Comment by bplight** [comment]
Thanks a lot! 
When do you plan to put new release 1.8.8 on your page http://joomla.unlikelysource.org/ ?

**Comment by andrewscaya** [comment]
Hello bplight,

We will make the new release available as soon as possible.  The delay is due to technical problems.

Thank you for your interest in the Simple Email Form Module.

Regards,
