### ISSUE TITLE
File uploaded in spite of wrong captcha

### ISSUE THREAD

**Issue by martinbeaudry** [andrewscaya/mod_simpleemailform#12]
Version: 1.8.8a

Bugs with file upload and captcha features:

1) When a wrong captcha is entered, the file is still uploaded.
2) User only receives a success message saying that the files have been downloaded if the following two conditions are true:
    - The last file upload button is used (first ones have no effect);
    - The captcha is wrong.

If the captcha is right, no message is sent.

**Comment by andrewscaya** [comment]
Bug Report
=========

Title:  File upload completes successfully despite a wrong captcha being submitted

Class: Bug

Date: 2016-07-22
Reported By: Martin

Product: Joomla, version: 3.5.1
Product: Simple Email Form, version: 1.8.8
Browser: All

Is it reproducible: Yes

Description
--------------
1) When a wrong captcha is entered, the file is still uploaded.
2) User only receives a success message saying that the files have been downloaded if the following two conditions are true: 
    - The last file upload button is used (first ones have no effect);
    - The captcha is wrong.

If the captcha is right, no message is displayed.


Steps to Produce/Reproduce
--------------------------
Submit a file to upload and enter a wrong captcha.


Expected Results
----------------
The user should receive a failure message.


Actual Results
--------------
File is uploaded, upload success message is displayed and wrong captcha message is also displayed.

**Comment by andrewscaya** [comment]
Whitebox testing the suggested patch.

**Comment by andrewscaya** [comment]
Blackbox testing the suggested patch.

**Comment by andrewscaya** [comment]
Release 1.8.9 is now frozen. Release candidate is under final review.

**Comment by andrewscaya** [comment]
Version 1.8.9 released.
