### ISSUE TITLE
JForm translations not explained well enough in documentation

### ISSUE THREAD

**Issue by martinbeaudry** [andrewscaya/mod_simpleemailform#17]
The documentation needs to explain how users can change the form language using Joomla instead of the "Default Language" field.

**Comment by andrewscaya** [comment]
Martin --

That's correct!  As previously discussed, the language settings are now integrated with Joomla's language settings by default.  In version 3.0.0, Simple Email Form's language setting will be removed along with the Classic mode.

Cheers!

Andrew

**Comment by andrewscaya** [comment]
Enhancement completed.
