### ISSUE TITLE
Confirmation message when uploading more than one file

### ISSUE THREAD

**Issue by martinbeaudry** [andrewscaya/mod_simpleemailform#2]
If the form allows the user to upload more than one file, the confirmation message saying that the file has been successfully uploaded is only displayed for the last file.

Confirmation message should be fine grained so that the user knows which files have been submitted and which have not.

**Comment by andrewscaya** [comment]
Added to the 2.0 milestone as one of 'A few minor frontend enhancements'.

**Comment by andrewscaya** [comment]
Whitebox testing the suggested patch.

**Comment by andrewscaya** [comment]
Blackbox testing the suggested patch.

**Comment by andrewscaya** [comment]
Release 1.8.9 is now frozen. Release candidate is under final review.

**Comment by andrewscaya** [comment]
Version 1.8.9 released.
