### ISSUE TITLE
Update the the end-user documentation.

### ISSUE THREAD

**Issue by andrewscaya** [andrewscaya/mod_simpleemailform#24]
Update the the end-user documentation.

**Comment by andrewscaya** [comment]
@martinbeaudry --

I have declared "codefreeze" status for version 2.1.0. Branch "2.1.0-doc" has now been created. You may modify the end-user documentation at your convenience!

Many thanks!

Yours,

Andrew

**Comment by martinbeaudry** [comment]
Good! I'll get back to you if I have any question.

Thanks to you!

**Comment by andrewscaya** [comment]
Closed by commit 0253986b5e6.
