### ISSUE TITLE
Maximum ram shooting to 128MB how to restrict to 20MB reasonable attachment size

### ISSUE THREAD

**Issue by interactive007** [andrewscaya/mod_simpleemailform#25]
Simple email form shows often 128MB file size for upload (using attachment configuration in advanced tab of module) but there is no configuration of managing file size definition there, which causes user to avail full server memory size. It is not recommended to use maximum server resources for sending email attachments.

Please upgrade to specify minimum and maximum filesizes of file attachments.

**Comment by andrewscaya** [comment]
Hi @interactive007 --

Maximum upload file size is a PHP level configuration setting. You can adjust this directive in your php.ini file of your Web server to fit your needs.

Thank you for your interest in the Simple Email Form module.

Best regards,

Andrew Caya
