### ISSUE TITLE
My own variables in Sender email, Email Title and Message

### ISSUE THREAD

**Issue by becart** [andrewscaya/mod_simpleemailform#26]
Hi, 
I want to add my own variables (from other joomla component) in Sender email, Email Title and Message.
Can you tell me which file I need to modify?

**Comment by andrewscaya** [comment]
Hi Becart --

You will find how to override rendering here : http://simple-email-form.readthedocs.io/en/stable/advanced_options.html#index-35.

Thanks for your interest in the Simple Email Form module!

Best regards,

Andrew
