### ISSUE TITLE
request for checkbox checked instruction

### ISSUE THREAD

**Issue by bplight** [andrewscaya/mod_simpleemailform#27]
Hello. Thank you very much for your extention mod_simpleemailform!
I wouв like to ask you to add information into Documentation (http://simple-email-form.readthedocs.io/en/stable/basic_options.html?highlight=checkbox) on how to set checkbox checked.
I foun in your code:
___________________
                foreach ($field['value'] as $key => $visible) {
                    $checked = (in_array($key, $value, true)) ? 'checked' : '';
                    $list = array($type, $name, $name, $key, $key, $cssInput, $checked, $this->padVisible($visible));
                    $output .= vsprintf('<input type="%s" name="%s[]" id="%s_%s" value="%s" class="%s" %s/>%s', $list);
                }
______________________
In admin panel I write in default value for this field: option1=text1,option2=text2
Please, give an example on how to make field with checkbox already set checked by default option2. I need it to use in term agreement.
Thank for you answer!

**Comment by andrewscaya** [comment]
Hello @bplight --

You can easily accomplish this by overriding the rendering process. You will find how to override rendering here : http://simple-email-form.readthedocs.io/en/stable/advanced_options.html#index-35.

Then, you would just need to add a line near the end of your tmpl/default_custom.php file that would simply add the appropriate HTML attribute (checked = "checked") to your checkbox input field.

Thanks for your interest in the Simple Email Form module!

Best regards,

Andrew
