### ISSUE TITLE
JForm form type not sending email

### ISSUE THREAD

**Issue by tlbearly** [andrewscaya/mod_simpleemailform#32]
The classic form works, but when I switch to JForm it does not send an email or redirect. No errors are reported on the javascript console. I am using Joomla 3.8.6, php 7.0.

**Comment by andrewscaya** [comment]
Hello @tlbearly,

Both the 'Classic' form and the 'JForm' form use the JMail object to send the email. Thus, if one works, the other should work also. Moreover, we test these parts of the module extensively and all our tests pass.

Please make sure that you entered the admin's email in the module's configuration and that you have configured at least one content field in your form.

If this still does not work, please write back to us.

Thank you for your interest in the Simple Email Form module.

Best regards,

Andrew

**Comment by tlbearly** [comment]
No, I have not been able to get it to work. 

Where do I enter the admin email?

Also, when the From address is not from the same domain as my website Gmail gives a warning.

I am using the default Joomla Captcha Recaptcha but the version is from 2011. Should I upgrade this somehow? I just upgraded Joomla to the newest version.

**Comment by AnneRe** [comment]
You can enter the admin e-mail here: Canfiguration/Global/"Tab" Server. Here can you find "Mail Settings".
I'm not sure. But I think the admin mail must match your domain.
Extensions should always be updated when prompted.

This functions with me also everything perfectly. 
I have an error message when the contact form is filled and is sent off. Then I am passed on on a new side. One stands on that only 0. However, no e-mail comes. 
A few weeks ago everything has still functioned.

SORRY for my BAD englisch -.-"

**Comment by tlbearly** [comment]
I set Display Size of Field to something other than 0 and it worked.

**Comment by tlbearly** [comment]
When there is no From address it displays "Error 0", error code of 0, no error message, and error status of 500 Internal Server Error.

This also happens when there is a From address with the Display Size of Field set to 0.

**Comment by AnneRe** [comment]
Ah. 
I found the mistake.
I did not have "from" in the field type of email.
Such a stupid mistake. SORRY and thank you very very much!!!

**Comment by andrewscaya** [comment]
@AnneRe Glad to see that everything is working for you now!

@tlbearly Have you tried following what is Joomla's suggested method for installing/configuring/using Google ReCaptcha? Please see here: [https://docs.joomla.org/J3.x:Google_ReCaptcha](https://docs.joomla.org/J3.x:Google_ReCaptcha).

**Comment by tlbearly** [comment]
It is working now. The problem was I set "Display Size of Field" to zero. Your popup note suggests to do this. Yes, I had set up Google ReCaptcha.
