### ISSUE TITLE
Copy to me : error

### ISSUE THREAD

**Issue by operon** [andrewscaya/mod_simpleemailform#34]
I do not receive a copy of the message.
the recipient get the message, the sender receive a message "Custom Message" after validate form

I have validated "Send Me an Email Fiel" activated but no copy of the message arrives at the sender.

**Comment by andrewscaya** [comment]
Hello @operon,

We will try to reproduce your issue over the next few days.

Thank you for your interest in the Simple Email Form module!

Best regards,

Andrew Caya

**Comment by andrewscaya** [comment]
@operon --

The module seems to work as expected. The "copy me" field allows the form submitter to receive a copy of the contents of the form that he/she is submitting.

Is your mail server configured to relay emails to other domains?

Could you please give us a little more information on your specific setup?

**Comment by operon** [comment]
Hello,

I reread the plugin and I think I understood that I was wrong.
  "Send Me an Email Field" works well

There is no function "send a copy of the message to the sender".

It would be nice to have a check box to activate the function.

**Comment by andrewscaya** [comment]
Hello @operon --

We will see if we can add this feature request somewhere in the future development plans of the Simple Email Form module.

Many thanks!

Best,

Andrew
