### ISSUE TITLE
Textarea Issue

### ISSUE THREAD

**Issue by jdowlan** [andrewscaya/mod_simpleemailform#35]
Hi there,

I'm having some issues getting a textarea input to work - It is trimming the input down. For example:
"Test message goes in here" gets trimmed to "<p>Test message goes"

Any assistance would be greatly appreciated.

Thanks,

Jacob 

![issue](https://user-images.githubusercontent.com/44305797/47245365-ae2f4c00-d444-11e8-9eda-df6cbdfd6466.PNG)

**Comment by andrewscaya** [comment]
Hi @jdowlan,

The input fields get trimmed to the field size as you have defined them in the Joomla administration panel.

Here is the section of the source code that does this in the JForm version of SEF:
https://github.com/andrewscaya/mod_simpleemailform/blob/bb5e73dd1219e6268ce630f70c2f3a73b687e66d/sefv2/modsimpleemailform.php#L1794

Please let us know if this answers your question.

Many thanks for your interest in the Simple Email Form module!

Best regards,

Andrew
