### ISSUE TITLE
Turn off 'Toggle Editor' on public page

### ISSUE THREAD

**Issue by chumphrey18** [andrewscaya/mod_simpleemailform#37]
My form is showing on a 'Contact Us' page.  There is a 'toggle editor' button that displays.  How do I remove that so that visitors to the website cannot see this?

**Comment by andrewscaya** [comment]
Hi @chumphrey18!

You can turn off the TinyMCE version of the form in Joomla's administration panel. It is usually found under 'Extensions -> Plugins -> Editor - TinyMCE '.

Please let us know if this answers your question.

Many thanks for your interest in the Simple Email Form module!

Best regards,

Andrew

**Comment by chumphrey18** [comment]
Thanks so much!!

________________________________

**Comment by andrewscaya** [comment]
@chumphrey18 You're welcome! :)
